TicketApp/config/routes.rb
Rails.application.routes.draw do
  resources :tickets
  root to: 'tickets#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

TicketApp/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

TicketApp/app/models/excavator.rb
class Excavator < ApplicationRecord
  belongs_to :ticket
end

TicketApp/app/models/ticket.rb
class Ticket < ApplicationRecord
  has_many :excavators
end

TicketApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

TicketApp/app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  def index
    @tickets = Ticket.all
  end
  def show
   @excavators = Excavator.where(ticket_id: params[:id])
  end
end

TicketApp/app/helpers/application_helper.rb
module ApplicationHelper
end

TicketApp/app/helpers/tickets_helper.rb
module TicketsHelper
end

TicketApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TicketApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

TicketApp/app/views/tickets/index.erb
<h1>Tickets</h1></br>
<div class="container">
  <table border="1">
    <tr>
    <th>RequestNumber</th>
    <th>SequenceNumber</th>
    <th>DateTimes</th>
    <th>ServiceArea</th>
    <th>DigsiteInfo</th>
    <th>Excavators</th>
    </tr>
   <tbody>
  <% @tickets.each do|ticket| %>
   <tr>
     <td> <%= ticket.RequestNumber %> </td>
     <td> <%= ticket.SequenceNumber %> </td>
     <td> <%= ticket.DateTimes.values.first %> </td>
     <td> <%= ticket.ServiceArea.values.first %> </td>
     <td> <%= ticket.DigsiteInfo.values.first %> </td>
     <td> <%= link_to 'Excavators', ticket_path(ticket) %> </td>

   </tr>
  <% end %>
   </tbody>
  </table>
</div>

TicketApp/app/views/tickets/show.erb
<h1>Excavators of Ticket</h1>
<div>
  <table>
    <tr>
      <th>CompanyName</th>
      <th>Address</th>
      <th>CrewOnsite</th>
    </tr>
    <tbody>
    <tr>
      <%@excavators.each do |exc| %>
      <td><%= exc.Excavator["CompanyName"]%></td>
      <td><%= exc.Excavator["Address"]%></td>
      <td><%= exc.Excavator["CrewOnsite"]%></td>
      <%end %>
    </tr>
    </tbody>
  </table>
  <%= link_to "Back", root_path %>
</div>